spring:
  application:
    name: hello-spring-api

  profiles:
    active: local

  config:
    import:
      - logging.yml
      - db-main.yml
---
  config:
    activate:
      on-profile: local
---
spring.config.activate.on-profile: local-dev
---
spring.config.activate.on-profile: dev
---
spring.config.activate.on-profile: staging
---
spring.config.activate.on-profile: live
