logging:
  level:
    org.springframework.web: DEBUG


spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0

logging.config: classpath:logback/logback-${spring.profiles.active}.xml